name: Notification
on: [pull_request]
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - name: get url
      uses: kceb/pull-request-url-action@v1
      id: pr-url

    - name: Slack Notification
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        author_name: Integration Test # default: 8398a7@action-slack
        fields: all
        mention: here
        if_mention: failure,cancelled
        text: "${{ steps.pr-url.outputs.url }}"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: always() # Pick up events even if the job fails or is canceled.
